### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by adamhsparks** [phytopathology/Reproducible.Plant.Pathology#12]
I've created branches for everyone following @zachary-foster's lead.

In the three I've created (I've not made any changes to yours, @zachary-foster), I have rearranged the files to that the package passes the build tests. To do that I moved the `article_data.csv` file to `inst/extdata`.

I've also added the missing DOI information to the `doi` field in this file in the branches I created and subset the files to be looked at by the assignee, _e.g._ `adams-changes` contains an `article_data.csv` that only has my 50 assigned articles in it.

I'll complete my changes here and then merge back with the master branch.

cheers!

**Comment by zachary-foster** [comment]
>I've created branches for everyone following @zachary-foster's lead.

Good idea with the branches. To make the best use of them, I had planed on submitting pull requests so that 
we can discuss any large changes, even though we all have the ability to edit master directly. For anyone who might not be used to dealing with branches and pull requests: branches are just alternate versions of the repository. One branch can be combined with another on your local computer using the `git merge` command. A pull request is just a `git merge` that is done by GitHub to the repository online, except that it requires permission from someone with write access to the repository. We all have write access, so pull requests are not actually necessary, but I think they provide a good way to discuss large changes. 

I still think we should make any minor edits directly to master so we dont over complicate things. 

Also, it will be easiest to deal with multiple branches if we merge them with master whenever some portion of the work is done, since the more divergent the branches get the harder it will be to merge them later. Merge conflicts are annoying to fix and can be minimized with frequent merging.   

> subset the files to be looked at by the assignee...

Im not sure, but this might make merging the branches difficult. Not a big deal, but something to consider. Then again, all of us editing the same file with different spreadsheet applications could throw off formatting details and lead to a merging nightmare, especially if anyone edits another person's row or reorders the spreadsheet, so maybe this is a better way to go about it.Talking with @grunwald the other day, we thought it might be most straight forward to have a Google Doc that we all edit. Once it is mostly done, we can export it to csv and commit it in the repository. Thoughts?

**Comment by zachary-foster** [comment]
P.S. we can still use the code in this repository to make the template for the google doc and fill in any information automatically that is present in the bibtex data.

**Comment by adamhsparks** [comment]
I was thinking about the branches and having separate files we work in. Merging them shouldn't create conflicts as long as we kept the same headings. 

However, the Google Docs approach has merit and there is this: https://github.com/jennybc/googlesheets, so yes, I think that's a better approach for sure. If that's the case, do we need separate branches for our own work?

**Comment by zachary-foster** [comment]
The googlesheets package looks cool, thanks. 

> If that's the case, do we need separate branches for our own work?

Not necessarily, but I find them useful to discuss major changes since the PR has a diff and an area for comments. Its a lot more work to describe exactly what you did or for others to look through the commit history. If fine with it either way. I had planned on submitting a PR soon for my branch and continuing on master until another big change came up

**Comment by adamhsparks** [comment]
Let's leave them for possible future use then. No need to remove them yet.

**Comment by zachary-foster** [comment]
Yea, they are not in the way.

**Comment by adamhsparks** [comment]
@zachary-foster, I took the changes you started in the vignette, merged them with my branch and now have this using _googlesheets_.

https://docs.google.com/spreadsheets/d/1HzgDMK1Q2GC9KviZIiDvhViG0d8kuzSMeqls8C6fk98/edit?usp=sharing

Still a bit more work to do, but we're well on our way. I'll get that sheet set up for sharing with everyone, gotta go home now.

**Comment by emdelponte** [comment]
@zachary-foster @adamhsparks I liked this idea of using googlesheets. It will facilitating collaborative editing and there is a solution for integration.

**Comment by adamhsparks** [comment]
In light of the suggestion here, using Google Sheets, I've deleted the branches that I created.

I've left yours, since you've created it, @zachary-foster.
